### ISSUE TITLE
proto

### ISSUE THREAD

**Issue by 89z** [MrChota/gplayapi#1]
where did this file come from:

https://github.com/MrChota/gplayapi/tree/main/src/main/proto

**Comment by MrChota** [comment]
Google Play Store protobuf API wrapper

**Comment by 89z** [comment]
thanks for the comment. Can you give more details? How can I produce the same file?

**Comment by MrChota** [comment]
> npm i google-play-proto

**Comment by 89z** [comment]
> npm i google-play-proto

I dont think this is true. For example, you have this line:

https://github.com/MrChota/gplayapi/blob/a34e4eba8e061482f94fef129e26cae900263f68/src/main/proto/GooglePlay.proto#L859

and the `google-play-proto` file, doesnt have that field:

https://github.com/dweinstein/google-play-proto/blob/01d5e5554c38806dc12b6d0ade8ef04b80e99140/googleplay.proto#L724-L742
